tasks = [
    # ── Easy / LOW urgency ─────────────────────────────────────────────────────
    {
        "job": "cotton harvesting",
        "required_skill": "cotton",
        "difficulty": "easy",
        "urgency": 1,
        "description": "Harvest mature cotton from 5-acre field before rainfall.",
    },
    {
        "job": "cotton boll collection",
        "required_skill": "cotton",
        "difficulty": "easy",
        "urgency": 1,
        "description": "Collect and bag cotton bolls from the drying yard for storage.",
    },
    {
        "job": "rice seedling sorting",
        "required_skill": "rice",
        "difficulty": "easy",
        "urgency": 1,
        "description": "Sort and grade rice seedlings before transplantation begins.",
    },
    {
        "job": "irrigation canal inspection",
        "required_skill": "water",
        "difficulty": "easy",
        "urgency": 1,
        "description": "Walk the irrigation canals and mark any blockages or breaches.",
    },
    {
        "job": "tractor pre-season maintenance",
        "required_skill": "tractor",
        "difficulty": "easy",
        "urgency": 1,
        "description": "Perform routine oil and filter checks on field tractors before sowing season.",
    },
    # ── Medium / MEDIUM urgency ────────────────────────────────────────────────
    {
        "job": "rice planting",
        "required_skill": "rice",
        "difficulty": "medium",
        "urgency": 2,
        "description": "Plant paddy seedlings across flooded fields within the monsoon window.",
    },
    {
        "job": "rice transplanting",
        "required_skill": "rice",
        "difficulty": "medium",
        "urgency": 2,
        "description": "Transfer paddy seedlings from nursery beds to main flooded fields.",
    },
    {
        "job": "drip irrigation setup",
        "required_skill": "water",
        "difficulty": "medium",
        "urgency": 2,
        "description": "Install and calibrate drip lines across a new 8-acre vegetable plot.",
    },
    {
        "job": "tractor ploughing",
        "required_skill": "tractor",
        "difficulty": "hard",
        "urgency": 2,
        "description": "Deep ploughing of hard soil before sowing season begins.",
    },
    {
        "job": "cotton weeding",
        "required_skill": "cotton",
        "difficulty": "medium",
        "urgency": 2,
        "description": "Manual inter-row weeding across 10 acres of standing cotton crop.",
    },
    {
        "job": "herbicide application",
        "required_skill": "spraying",
        "difficulty": "medium",
        "urgency": 2,
        "description": "Apply herbicide between cotton rows to suppress weed growth.",
    },
    {
        "job": "bund repair and levelling",
        "required_skill": "tractor",
        "difficulty": "medium",
        "urgency": 2,
        "description": "Repair and re-level field bunds using tractor blade before monsoon.",
    },
    # ── Hard / HIGH urgency ────────────────────────────────────────────────────
    {
        "job": "pesticide spraying",
        "required_skill": "spraying",
        "difficulty": "hard",
        "urgency": 3,
        "description": "Emergency pesticide spraying to control locust outbreak across 12 acres.",
    },
    {
        "job": "fungicide treatment",
        "required_skill": "spraying",
        "difficulty": "hard",
        "urgency": 3,
        "description": "Urgent foliar fungicide application to control blast disease in standing rice.",
    },
    {
        "job": "flood irrigation management",
        "required_skill": "water",
        "difficulty": "hard",
        "urgency": 3,
        "description": "Manage drip and flood irrigation channels for drought-affected crops urgently.",
    },
    {
        "job": "emergency cotton defoliation",
        "required_skill": "cotton",
        "difficulty": "hard",
        "urgency": 3,
        "description": "Apply defoliant spray before mechanical harvesting in adverse weather window.",
    },
    {
        "job": "waterlogging drainage",
        "required_skill": "water",
        "difficulty": "hard",
        "urgency": 3,
        "description": "Emergency pumping and channel diversion to drain waterlogged paddy fields.",
    },
    {
        "job": "subsoil deep tillage",
        "required_skill": "tractor",
        "difficulty": "hard",
        "urgency": 3,
        "description": "Break compacted subsoil layer using chisel plough before late kharif sowing.",
    },
    {
        "job": "aerial-equivalent boom spraying",
        "required_skill": "spraying",
        "difficulty": "hard",
        "urgency": 3,
        "description": "High-pressure boom spraying of insecticide across 20-acre mango orchard.",
    },
    {
        "job": "rice stubble incorporation",
        "required_skill": "tractor",
        "difficulty": "medium",
        "urgency": 2,
        "description": "Shred and incorporate rice stubble into soil using rotavator before next crop.",
    },
]